### ISSUE TITLE
s

### ISSUE THREAD

**Issue by aiden-dev** [AllTheMods/ATM-4#101]

**Comment by Asshall** [comment]
Do you have a legit minecraft launcher ?
If yes try deleting your ".minecraft" 
If not download the server files and the client-side mods from the normal files ( do the difference from the modlist file )

**Comment by BaconBoi12131** [comment]
I tried deleting my .minecraft folder, however that still didn't work. I just realized that that error message pops up any time I try to download packs that are minecraft version 1.14.4. All other packs that are not 1.14.4 download without a problem.

**Comment by BaconBoi12131** [comment]
> Do you have a legit minecraft launcher ?
> If yes try deleting your ".minecraft"
> If not download the server files and the client-side mods from the normal files ( do the difference from the modlist file )

I tried deleting my .minecraft folder, however that still didn't work. I just realized that that error message pops up any time I try to download packs that are minecraft version 1.14.4. All other packs that are not 1.14.4 download without a problem. I also noticed that when trying to make a custom profile with the version 1.14.4, there is no error message, but the profile never shows up.

**Comment by BaconBoi12131** [comment]
Update: I figured out what was wrong but I have never seen anything like this before. For some reason it wouldn't work was because I needed to go to Users\user\Twitch\Minecraft\Install and I had to open minecraft.exe to finish installing. I have no idea why this is the case, and right now it seems like I'm the only one with this issue, which might be because I recently moved to a new computer. Hope this helps someone in the future!

**Comment by LezChap** [comment]
#BlameTwitch  All launchers seem to be having various problems with 1.14 tho.

**Comment by arnoproblems** [comment]
> 
> 
> Update: I figured out what was wrong but I have never seen anything like this before. For some reason it wouldn't work was because I needed to go to Users\user\Twitch\Minecraft\Install and I had to open minecraft.exe to finish installing. I have no idea why this is the case, and right now it seems like I'm the only one with this issue, which might be because I recently moved to a new computer. Hope this helps someone in the future!

You were not the only one with this issue. I had the same issue with the same situation. I also just moved to a new computer. Thanks for your post because it became my easy solution instead of me spending all night banging my head against a wall.

**Comment by forthwist** [comment]
> > Update: I figured out what was wrong but I have never seen anything like this before. For some reason it wouldn't work was because I needed to go to Users\user\Twitch\Minecraft\Install and I had to open minecraft.exe to finish installing. I have no idea why this is the case, and right now it seems like I'm the only one with this issue, which might be because I recently moved to a new computer. Hope this helps someone in the future!
> 
> You were not the only one with this issue. I had the same issue with the same situation. I also just moved to a new computer. Thanks for your post because it became my easy solution instead of me spending all night banging my head against a wall.

Sammme.  Saved a bunch of frustration!  <3

**Comment by Chikimuras** [comment]
Not working for me

**Comment by jazzypancake** [comment]
I am having this issue and used the solution that op stated and it worked! Thanks!

**Comment by greenja4** [comment]
Created an account to say, found this on a reddit thread. Anyone here NOT have Java for their computer, or had it removed? Try re-installing Java if you haven't... Can't believe I didnt' think of this one. https://java.com/en/download/
