### ISSUE TITLE
crash at the start 

### ISSUE THREAD

**Issue by exect01** [AllTheMods/ATM-4#11]
so i press the button so the game start to load the game i crashed instantly
![Screenshot_13](https://user-images.githubusercontent.com/55636942/65378597-0001d700-dc91-11e9-94ee-1200e34e2530.png)

**Comment by Tfarcenim** [comment]
need the log

**Comment by Longtooths** [comment]
I am getting same error, no crash log and not even a crash folder. This is using the Twitch Loader. Have a friend that is loading and accessing same server as me and he has no issues. I hate him right now!

**Comment by Alucabr** [comment]
I have the same problem with this modpack and with all modpacks in version 1.14.4, those in version 1.12.2 open normally.

**Comment by Yamza** [comment]
Try GDLauncher instead. Twitch has issues with 1.14 in general.

**Comment by Alucabr** [comment]
unfortunately no modpack on 1.14.4 has response support, and to make matters worse on my pc no modpack on 1.14.4 opens.

**Comment by Yamza** [comment]
Did you try GDlauncher?

**Comment by Alucabr** [comment]
@Yamza GDlauncher dont work for me,
no modpack finishes installing it, and my internet is pretty fast.

**Comment by Yamza** [comment]
Only option then is to get the forge files from someone who can install a 1.14.4 pack and install them in the proper location for twitch to use them. You'll have to do this for every pack/update though.

**Comment by exect01** [comment]
why closed if the problem its not fixed?

**Comment by exect01** [comment]
i still cannot get pass the error even in the current version
![imagen](https://user-images.githubusercontent.com/55636942/68561736-977bde80-0425-11ea-95c1-264fb3aec13e.png)
![imagen](https://user-images.githubusercontent.com/55636942/68561755-b37f8000-0425-11ea-99bd-155462915e4f.png)
