### ISSUE TITLE
Optifine compatibility

### ISSUE THREAD

**Issue by zKeyzz** [AllTheMods/ATM-4#114]
How can my friends and I play the mod pack with optifine (shaders) in the 0.3.0 version?
We have tried to add optifine in the mods folder but when we start the game it says that it's not compatible. We are using Forge 28.1.107 btw.

Thanks for your help!

**Comment by tonioqiu** [comment]
I use optifine F5 on 0.3.0 with forge 28.1.109

**Comment by Eld0r** [comment]
I was able to use it with forge 28.1.109 on atm4 0.3.2.
But the refined storage blocks got lighting issues and I deleted the jar from my client again.
