### ISSUE TITLE
Unable to launch forge or any mods

### ISSUE THREAD

**Issue by GlowRS** [AllTheMods/ATM-4#120]
hey for some reason I am unable to launch this pack and I don't know why. other packs work fine it's just this one. https://www.youtube.com/watch?v=aAYgt8NtCKM here is a video of what is happening

any idea how to fix?

**Comment by xtreemninja** [comment]
any ideas on how to fix?

**Comment by furtabs** [comment]
other packs work fine


Are other packs 1.14+ packs. Twitch launcher doesn’t handle them well. Try using gdlauncher http://gdevs.io
