### ISSUE TITLE
REALLY easy dupe glitch

### ISSUE THREAD

**Issue by Joelifer123** [AllTheMods/ATM-4#13]
This is a really easy dupe glitch which I am 99.999% sure is unintentional and hence should be fixed
all you need is at least 2 canvas bags (from blue power).
The glitch happens because the canvas bags stack when they have the same nbt.
When holding multiple canvas bags in your hand, if you open them and place an item inside, and then you split the stack, e.g. you have 1 diamond and you open 2 bags (at once), then you lace the diamonds in, now both bags have a diamond in so if you split them and open them individually, taking the diamond out, you now have 2 diamonds.
This is just too easy and needs to be patched pretty quickly.

quick walkthrough of the glitch if you need it:

![Minecraft-1 14 4-2019-09-25-21-27-39](https://user-images.githubusercontent.com/54853535/65637326-e5569780-dfdb-11e9-869a-40bef2f8a2fa.gif)

**Comment by Darkere** [comment]
What version are you on?
present in 0.1.2b

**Comment by Joelifer123** [comment]
Im on 0.1.2b
