### ISSUE TITLE
Cannot update or install via twitch 

### ISSUE THREAD

**Issue by Aughen** [AllTheMods/ATM-4#133]
I have tried 5 other packs and they all work fine, but when installing the latest ATM4 I get the error The system cannot find the file specified. not sure what the issues is but it seems to be just with this modpack. 

Any help would be great. 

What i have tried:

- deleted all instances of minecraft from twitch and file directories

- reinstalled java 

- reinstalled twitch launcher

- verified it is with multiple versions of ATM4

- do not know were the log files are to look at?

**Comment by Snowy556** [comment]
I am having the same problem, it looks to be an issue with the forge version the modpack is looking for.
First launch, the error is:
 Failed to find Minecraft resource version 1.14.4-20190829.143755 at D:\Program Files (x86)\Minecraft\Install\libraries\net\minecraftforge\forge\1.14.4-28.2.0\forge-1.14.4-28.2.0-client.jar
This is correct, this jar file is missing from the install directory. 

If I copy it there, the next error message is:
Failed to find Minecraft resource version 1.14.4-20190829.143755 at D:\Program Files (x86)\Minecraft\Install\libraries\net\minecraft\client\1.14.4\client-1.14.4-extra-stable.jar
To me this says it can't find a vanilla install here. I downloaded 1.14.4 to this folder, and launched it.
No Change.

I went to Forge's website, and got the 1.14.4-28.20 installer jar, and ran this pointed at my D:\Program Files (x86)\Minecraft\Install folder, and now the modpack runs.

I think there might be an issue where forge installs itself if you have multiple drives, and you install ATM to a non-standard locatio
[First launch fresh.log](https://github.com/AllTheMods/ATM-4/files/4209016/First.launch.fresh.log)
[2020-02-15-1.log.gz](https://github.com/AllTheMods/ATM-4/files/4209017/2020-02-15-1.log.gz)
[2020-02-15-2.log.gz](https://github.com/AllTheMods/ATM-4/files/4209018/2020-02-15-2.log.gz)


n.

**Comment by LezChap** [comment]
Twitch has issues with installing Forge.  It's a problem with the Twitch App that has been an issue for months, and we have no control over.

Some possible solutions:
1. Install Forge manually in your Twitch App's minecraft folders.
2. Remove the Twitch App's minecraft folders to try to force it to download and install properly.
or
3. Use a different launcher.  GDLauncher and ATLauncher both support imports of CurseForge pack zips.

**Comment by junkerprime** [comment]
There is definitely a problem with twitch/forge integration. Even if you create a custom Profile and simply set the version for 1.15.2, and latest version of forge, and no mods, It will crash because of the missing files.   If you know what you are doing and install forge manually it works fine.

**Comment by furtabs** [comment]
I’m going to close this issue. This isn’t “our fault”. It has to do with forge codes the installer to not like when Usernames have Spaces but also that twitch just sucks and can not handle the new installer. We support the use of GDLauncher http://gdevs.io and this really we can’t fix
