### ISSUE TITLE
Unable to launch the server

### ISSUE THREAD

**Issue by SentinelKdog** [AllTheMods/ATM-4#135]
when you double click the batch file it pops open for a second then closes

**Comment by SentinelKdog** [comment]
Error occurred during initialization of VM
Could not reserve enough space for 4096000KB object heap

**Comment by SentinelKdog** [comment]
i can only get it to launch with one gig of ram then it crashes

**Comment by Revvilo** [comment]
Please check that you have 64bit java installed

**Comment by SentinelKdog** [comment]
> Please check that you have 64bit java installed

How do i do that :)

**Comment by Revvilo** [comment]
If you're on windows, go to `Add or Remove programs` and search for java

**Comment by SentinelKdog** [comment]
> If you're on windows, go to `Add or Remove programs` and search for java
It just says java 8 it doesnt say 64 or 32 bit

**Comment by Revvilo** [comment]
Ok, well you have 32 bit then. 64 bit shows as `Java <version and stuff> (64 bit)`. 
Here's the download for 64 bit java. If you still have issues, then try uninstalling the other 32bit version.
https://javadl.oracle.com/webapps/download/AutoDL?BundleId=241536_1f5b5a70bf22433b84d0e960903adac8

**Comment by SentinelKdog** [comment]
youre the best how do i repay you :D

**Comment by Revvilo** [comment]
Haha, my pleasure. Have you got it working then?

**Comment by SentinelKdog** [comment]
Yes

Sent from Yahoo Mail on Android 
 
  On Mon, Feb 24, 2020 at 5:57 PM, Revvilo<notifications@github.com> wrote:   
Haha, my pleasure. Have you got it working then?
