### ISSUE TITLE
Blueprints for immersive eng

### ISSUE THREAD

**Issue by ShimaiTsukino** [AllTheMods/ATM-4#140]
I have a server that I am running, just started it less than a week ago. One of my players started getting in to Immersive Eng and has noticed that blueprints are not working right and he can not make vaccume tubes. Im sure there is somewhere in the configs that I can fix it but I am not sure where.. Any help would be nice.. I am kinda a newbie to running my own Minecraft server.. 

## Expected Behavior
When a blueprint is formed it SHOULD have flavor text as to what it does, but just comes out blank.

## Current Behavior
comes out blank then also messes with the players inventory every time he grabs it, almost glitching it.

**Comment by whatthedrunk** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/3833 Once the mod updates I will make sure to update the pack.

**Comment by ShimaiTsukino** [comment]
Thank you so much! Sorry i missed that post, my player brought it up right after i was off work .. so i may have only looked at a couple posts...
