### ISSUE TITLE
modpack don't open

### ISSUE THREAD

**Issue by Alucabr** [AllTheMods/ATM-4#15]
https://pastebin.com/zenEy6aq

No crash log is created, just the normal log. modpack does not even open and an error message appears and returns to the launcher vanilla. all 1.12.2 modpacks open normally, but all the mods 4 or any other from 1.14.4 does not open.

**Comment by Yamza** [comment]
Issue is with twitch, try gdlauncher instead or see https://github.com/AllTheMods/ATM-4/issues/11.

**Comment by Alucabr** [comment]
@Yamza you again? i say alot GDLauncher dont work for me haha

**Comment by Yamza** [comment]
Why are you opening another issue for the same thing? I already gave you the solutions. If they are not working you'll need to contact twitch support. I've already done that almost 2 months ago and still haven't got a reply.

**Comment by Alucabr** [comment]
You can only be kidding right, to post my log, and it was because someone asked to see, you are not helping at all, minecraft game with mods for years, and never had that kind of problem.

**Comment by Yamza** [comment]
The log says forge is not properly installed.

**Comment by drizzs** [comment]
Yamza is right, the issue is with twitch for sure. The load stops before it even starts the pack files.

[19:54:11] [main/FATAL]: Failed to find Minecraft resource version 1.14.4-20190829.143755 at D:\A Curse\curse\Minecraft\Install\libraries\net\minecraftforge\forge\1.14.4-28.1.20\forge-1.14.4-28.1.20-client.jar

You can try reinstalling Twitch, or forge, or minecraft. The issue is on your end. If you want to play ATM4 which is an amazing pack, you should try the steps to fix it on your end!

**Comment by thecrescentkid** [comment]
I got a tip you can use the Atlauncher to use curse URL or download the zip file and you can load it into the launcher.

**Comment by Alucabr** [comment]
> I got a tip you can use the Atlauncher to use curse URL or download the zip file and you can load it into the launcher.

yes, work, 
thanks for helping, strange to have to rely on third party launcher, and the partner launcher where the mods is hosted does not work haha

**Comment by sjgold** [comment]
for whatever its worth I am getting the same error with any 1.14 pack using the twitch launcher.

**Comment by Yamza** [comment]
Solution is here: https://www.reddit.com/r/TeamRam/comments/dsxpzo/modpack_launcher_guide_1144/

**Comment by sjgold** [comment]
> Solution is here: https://www.reddit.com/r/TeamRam/comments/dsxpzo/modpack_launcher_guide_1144/

so the file is in the proper directory forge-1.14.4-28.1.85.jar is where it is looking for it, but it does not recognize it. This does not occur for mods at 1.12....

**Comment by Yamza** [comment]
That is correct.

**Comment by exect01** [comment]
> 
> 
> > Solution is here: https://www.reddit.com/r/TeamRam/comments/dsxpzo/modpack_launcher_guide_1144/
> 
> so the file is in the proper directory forge-1.14.4-28.1.85.jar is where it is looking for it, but it does not recognize it. This does not occur for mods at 1.12....

some idiot deleated the usefull stuff

**Comment by exect01** [comment]
> 
> 
> Solution is here: https://www.reddit.com/r/TeamRam/comments/dsxpzo/modpack_launcher_guide_1144/

some idiot deleated the usefull stuff
and the ATlauncher dosnt work 4 me

![imagen](https://user-images.githubusercontent.com/55636942/68564501-8cc64700-042f-11ea-9458-279a8bcac68f.png)
