### ISSUE TITLE
Crashes upon launch

### ISSUE THREAD

**Issue by Pizzanator** [AllTheMods/ATM-4#17]
Trying to launch ATM4 v0.1.5 on the twitch launcher. Launches the MC laucher successfully. But crashes before the game window pops up. Running windows 10 on a PC.
[latest.log](https://github.com/AllTheMods/ATM-4/files/3721547/latest.log)

**Comment by Darkere** [comment]
Your forge install is missing a file. So far the only solution I've heard about was getting that file from someone else. 

Though it's possible that deleting the install folder and forcing things to reinstall can help.

**Comment by Pizzanator** [comment]
Is it possible for you to link me the file?

**Comment by Pizzanator** [comment]
I found a solution, it seams downloading the forge installer, and installing the client version into Twitch_Launcher/Install folder adds the needed file. http://files.minecraftforge.net/

**Comment by Pizzanator** [comment]
So I fixed the original issue, however it's still crashing. The same way it did before
[latest.log](https://github.com/AllTheMods/ATM-4/files/3722670/latest.log)

**Comment by Darkere** [comment]
You broke something by installing forge over the existing forge install. It might be possible to install forge to a normal vanilla install and grab just the missing file.

**Comment by Yamza** [comment]
From my own testing it is not actually possible to fix twitch.

**Comment by Pizzanator** [comment]
Resetting forge and copying the missing file worked. Muchly appreciated.
