### ISSUE TITLE
serverstarter-1.2.7-forge-1.14.4.jar  file is not able to ping. 

### ISSUE THREAD

**Issue by jheugh** [AllTheMods/ATM-4#18]
serverstarter-1.2.7-forge-1.14.4.jar
Centos Linux  7.7.1908.
server starter jar file is not able to use ping. 
I can ping successfully to 8.8.8.8 and 1.1.1.1 manually. 
no outbound firewall or proxy. 

![ping-fail](https://user-images.githubusercontent.com/6596568/66795238-02430400-eed2-11e9-8a13-5ab322330a4f.png)

**Comment by Yamza** [comment]
Have you put an IP in the server properties file? If so, remove it.

**Comment by FallenEagle1** [comment]
https://github.com/AllTheMods/ServerStarter/issues/10
Can get around it by turning off the online check
