### ISSUE TITLE
Mobs highlighted through the map

### ISSUE THREAD

**Issue by CroissantSalad** [AllTheMods/ATM-4#19]
I can see every friendly and enemy mobs highlighted through the map, even ones that are far away or deep underground, surely this is not an intended feature.

Is there any mod I can turn off or config to change to fix this ?

Thanks in advance for your help

![Screenshot (194)](https://user-images.githubusercontent.com/56583148/66815829-41f10680-ef39-11e9-9b22-42f1d8c1e9b2.png)

**Comment by CroissantSalad** [comment]
In addition to this, the highlighted mobs seem to have an effect around them called "Glowing". This happens only in some random zones over an area of about 200 blocks. When I change from FPS to TPS view, my character is also highlighted (Glowed effect) in the affected zone.

Image bellow shows the swirl effect :
https://imgur.com/RtgTvJt

https://imgur.com/a6wfzVH

**Comment by robsonld04** [comment]
Im not 100% which mod adds it but there are special mobs (bosses) that come with enchanted gear with special effects (like glowing) im pretty sure its these mobs that are causing it in an AOE

**Comment by Darkere** [comment]
Apotheosis is the mod that adds these bosses.

**Comment by DietmarKrause** [comment]
the same problem in ftb unstable 1.14. As far as i know both have apotheosis.

**Comment by whatthedrunk** [comment]
Working with the mod devs to fix this. There is a cross mod issue.

**Comment by whatthedrunk** [comment]
Should be fixed let me know if you still see in 0.2.0
