### ISSUE TITLE
DUPE everything with no limits

### ISSUE THREAD

**Issue by daddyoff** [AllTheMods/ATM-4#20]
using a drying rack, in combination with a hopper, any kind, will get you virtually an infinite amount of items, depending on what you put, but pretty much anything you have more than 2 of, you can duplicate it.

I'm also playing on the latest version so far. 0.1.5

**Comment by Darkere** [comment]
already fixed by moddev
https://github.com/SilentChaos512/Silents-Mechanisms/issues/30
