### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by Mezhona** [AllTheMods/ATM-4#21]
Tried to download it from the twitch client, and got error "The system cannot find the file specified" when it was done trying to validate files.

No matter what version I tried downloading it gave me this error.
Any other mods works fine.

**Comment by Darkere** [comment]
already fixed by moddev
https://github.com/SilentChaos512/Silents-Mechanisms/issues/30

**Comment by Darkere** [comment]
The easiest fix is to just go with a different launcher like the gdlauncher.

It is possible to fix it by downloading and installing forge and moving the missing files from there into the twitch installation.
