### ISSUE TITLE
Mystical Agriculture: Master Infusion Crystal vanishes after a single use

### ISSUE THREAD

**Issue by MilesTFox** [AllTheMods/ATM-4#24]
Mystical Agriculture: 

Regular infusion crystal counts down uses as expected.

Master infusion crystal vanishes after a single use.

**Comment by MilesTFox** [comment]
Additional: Was using it in Simple storage network table.

**Comment by MilesTFox** [comment]
mysticalagriculture:master_infusion_crystal

**Comment by Darkere** [comment]
Will be fixed next update 
https://github.com/BlakeBr0/MysticalAgriculture/issues/232
