### ISSUE TITLE
Portality still broken

### ISSUE THREAD

**Issue by MisterSmileyFace** [AllTheMods/ATM-4#25]
I have contacted the mod author and they knew about the issue and released an update to fix it. This was a couple weeks ago. I was really hoping this updated would update that mod to the later version so that we can use Portality. Right now Portality is completely useless with no function. If for some reason you are not able to update to the working version, then can you remove the mod from the pack?

**Comment by Darkere** [comment]
IIRC the portal needs to face a certain direction to work (north I think?).
Direwolf played with it here: https://www.youtube.com/watch?v=fkkj4Bmc7II
