### ISSUE TITLE
YAMDA Portal block not responding on right click

### ISSUE THREAD

**Issue by DietmarKrause** [AllTheMods/ATM-4#26]
the mining dimension does not open on right click in an old world. In the save folder there should be  a Yamda folder as far a s i know but there isnt one. Perhaps a modf interaction.

**Comment by Tbizla** [comment]
Same problem on the ATM-4 server, i submitted a bug report on the YAMDA github page.

**Comment by DietmarKrause** [comment]
i have to add: after the first try to open the portal i restarted the modpack (not only the world) which lead to a crash with YAMDA in the log. somehow Forge doesnt like the mod in our version. After a simple retry the modpack could be started wihout any problem but the portal was not working. In the modpack ftb unstable 1.14 Yamda is working. In That pack there is a yamda folder within the save / world file. i could not find that folder in atm4 ...

**Comment by Tbizla** [comment]
Updating YAMDA to 4.1.1 seems to fix the issue. just tested it and it works at least for single player.

**Comment by DietmarKrause** [comment]
the portal seems to work after updating to Vers. 4-0.1.8b
