### ISSUE TITLE
Grass Texture

### ISSUE THREAD

**Issue by PryonTrets** [AllTheMods/ATM-4#29]
After updating to the newest version of the pack, all of the grass textures in my world have changed (to a vibrant green or in some cases, a pale green) for whatever reason. This carried over into my other world saves on other modpacks, and brand new & old worlds alike. However it did not transfer to Vanilla. Any help would be much appreciated :)

**Comment by Boomflex** [comment]
Hey @PryonTrets it is the latest Quark update which adds a "greener grass".

Line 898 of the Quark config has "Greener Grass = true", change that to false if you want it to go back.
