### ISSUE TITLE
When you teleport from another dimension to overworld, all XP appears to have vanished.

### ISSUE THREAD

**Issue by MilesTFox** [AllTheMods/ATM-4#32]
When you teleport from another dimension to overworld, all XP appears to have vanished.

Loging out and back in fixes it.

**Comment by Boomflex** [comment]
That is a Vanilla bug that has been around for years. 

Not a pack issue.

https://bugs.mojang.com/browse/MC-124177
https://bugs.mojang.com/browse/MC-132543
