### ISSUE TITLE
When more than 5 people are online the server, it lags

### ISSUE THREAD

**Issue by GrimmDZ** [AllTheMods/ATM-4#37]
It just started happening recently, as the server has gotten a lot players now. Most people experience block lag, and/or a minor delay. When more than 5 people are online. Wtd restarted it last night and it helped a bit but not much. Theres about an average of 8 or 9 people on since yesterday, or two days ago. when they all started coming in. Yesterday, the tps was around 9 I think.

**Comment by urikkiru** [comment]
Try increasing the amount of ram allocated to the server in the server-setup-config.yaml file.
