### ISSUE TITLE
[ATM4 -0.2.0] Druidcrafts Dreadfish swimming in mid-air in YAMDA mining dimension

### ISSUE THREAD

**Issue by DietmarKrause** [AllTheMods/ATM-4#39]
the last update of druidcraft added "Dreadfish" which are "swimming" in the air in YAMDA dimension. I havent seen them elsewhere until now. This seems to be a bug.

**Comment by VulpTheKangaFox** [comment]
Stated on Druidcraft's bugtracker but I'll mention here too. Dreadfish are meant to fly.

**Comment by noobanidus** [comment]
If your issue is that they're spawning in the YAMDA dimension, it's probably because they're spawning there when perhaps they shouldn't, which is an entirely different issue.
