### ISSUE TITLE
MysticalAgriculture no recipes in JEI

### ISSUE THREAD

**Issue by InflamedSebi** [AllTheMods/ATM-4#44]
Mystical agriculture has no recipes for seeds, or at least they are not shown in JEI.
They are supposed to be made with the infusion altar but without a recipe kinda impossible ...

**Comment by oly2o6** [comment]
This is an issue with the mod itself as the mod is in alpha it has not all been implemented

**Comment by WiiZavV** [comment]
This happend only on ATM4 servers, in single player recipes for mystical and plant tech show up as expected.

Workaround :
You can start a single player session and then connect to the server to make it work as long as you dont close your game.

**Comment by whatthedrunk** [comment]
This is said to be fixed but please reopen if needed.
