### ISSUE TITLE
Server Installation on hosted / dedicated Server only Demo Mode

### ISSUE THREAD

**Issue by Curlz242** [AllTheMods/ATM-4#45]
hi there,

I installed the server locally, renamed the forge***.jar to minecraft_server.jar and upload all folders and files to my server.
But it only starts in Demo Mode. (and change the server.properties - ports)

Any idea why?

**Comment by urikkiru** [comment]
Why would you rename the forge jar? That's not the proper way to install the server. Simply download the server file zip onto your server, unzip the folder, and run the start server script. Viola.

**Comment by Curlz242** [comment]
hi urikkiru,
the server is a hosted server and I do not have root rights to start a script. They've got their own server script and ways to handle jars. 
But thanks for reminiding, it is all working now. Theier "performance mode" changes JAVA arguments / JAVA handling. It is now fixed. 
Case can be closed. Thx.
