### ISSUE TITLE
Losing my xp levels when teleporting from the nether to the overworld

### ISSUE THREAD

**Issue by GrimmDZ** [AllTheMods/ATM-4#47]
I have noticed this when I tp back to my base or go back to the overworld not using the nether portal. From the nether. I have to either go back, and go through the portal or get xp to trigger it again. After I get xp its back. Its in the test server.

**Comment by Boomflex** [comment]
Repost of a previous error.

Not a pack error, this is a fundemental Vanilla issue.

You dont "lose" your XP levels, just the visual of them.

https://github.com/AllTheMods/ATM-4/issues/32

**Comment by GrimmDZ** [comment]
Ahhh didnt know someone already made this, sorry!
