### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by ScrambledGamer** [AllTheMods/ATM-4#5]
RFTools Power coal generator missing textures on all sides besides front, front texture also disappears when in use.
ComputerCraft noisy and crafty turtles (both normal and advanced) missing part of the texture.
edit: (Also reported to mod creators)

**Comment by ScrambledGamer** [comment]
can be fixed by adding/re-enabling RFTools Base

**Comment by drizzs** [comment]
I think this is a forge stability issue, forge just isn't technically a full release it still has bugs.
