### ISSUE TITLE
Couple of bugs. (Maybe)

### ISSUE THREAD

**Issue by FastHit** [AllTheMods/ATM-4#51]
So i have been playing this modpack for 2 days, and i noticed some bugs.
1. Mining Gadget Void filter do not delete the items if you set it to blacklist mode.
2. You cannot config a mod inside the game, Most annoyingly JEI. (Intended)

**Comment by Spivyyy** [comment]
> So i have been playing this modpack for 2 days, and i noticed some bugs.
> 
> 1. Mining Gadget Void filter do not delete the items if you set it to blacklist mode.
I discovered a similar bug, for me it will only delete 1 item on blacklist, but only if I have 1 item in the list. If I have 2 items in the list and set it to blacklist it deletes nothing.
