### ISSUE TITLE
crash on startup ;/

### ISSUE THREAD

**Issue by ghost** [AllTheMods/ATM-4#54]
hello i have a big problem that when i launch the all the mods 4 modpack it crashes on startup ;c
here is the crash log : https://pastebin.com/bWb7DEmy
please help because i really like this modpack

**Comment by ghost** [comment]
pls help i want to play it

**Comment by whatthedrunk** [comment]
If you have a full crashlog get me a pastebin of it all but see if one of these works for you as twitch is a pain in 1.14.4 

Alternatives that support Twitch imports
AtLauncher
https://atlauncher.com/downloads

GDLauncher
https://gdevs.io/
