### ISSUE TITLE
wont even start 

### ISSUE THREAD

**Issue by mythical01** [AllTheMods/ATM-4#55]
Instance update failed because: Component metadata update task failed while downloading from remote server:
Job 'Download of meta file net.minecraftforge/28.1.96.json' failed to process:
https://meta.multimc.org/v1/net.minecraftforge/28.1.96.json

**Comment by ghost** [comment]
1.14.4 modpacks don't work on multimc, if twitch doesn't work for you; you can try gdlauncher from this link: https://gdevs.io/
