### ISSUE TITLE
Server crashes every time after joining.

### ISSUE THREAD

**Issue by ghost** [AllTheMods/ATM-4#57]
I don't know much about this but every time I join my server that is hosted by Akliz my server crashes. Here is the crash report.
[crash-2019-12-09_03.55.57-server.txt](https://github.com/AllTheMods/ATM-4/files/3937829/crash-2019-12-09_03.55.57-server.txt)

**Comment by Knoxxar** [comment]
1. diasble solarflux
2. replace the block on position -105,68,261 with something else
3. enable solarflux

Worked for my server
