### ISSUE TITLE
0.2.5 Release Vanilla Chest are Quark Oak chest Cannot Craft Hoppers

### ISSUE THREAD

**Issue by J-Hoff389** [AllTheMods/ATM-4#59]
Unable to use the Quark Oak Chests in the Hopper recipe. Vanilla chest is still in recipe, but crafting it makes the Quark Oak Chest. Other Quark mod chests appear in the recipe rotation.

Quark Mod version r2.0-200
Forge 28.1.104

**Comment by Based199** [comment]
This is also an issue with crafting drawers. JEI says it accepts any chest, even cycles through all the Quark chests, except for the oak chest (from quark). any other chest works to craft the chest just fine.

**Comment by Uginsecond** [comment]
Can`t craft Strainer base - same chest problem... Asked for vanilla chest only.
Version - ATM4 0.2.5

**Comment by J-Hoff389** [comment]
I found this on Quark [feature list](https://quark.vazkii.net/#features). I will try it and if it works we can close. give me a minute

> Chests can be made of all the different wood types. Each one is styled differently for the type of wood you use. To get the vanilla chest, you can **craft a chest with more than one type of wood**, or woods added by other mods.

**Comment by Uginsecond** [comment]
It WORK !!!

**Comment by J-Hoff389** [comment]
That's great! so as long as you have any combination of different wood types you get a Vanilla Chest.

**Comment by alimoncul** [comment]
Why in the world you close this? Crafting recipe should accept any type of chests ??
