### ISSUE TITLE
Nether Portal bug

### ISSUE THREAD

**Issue by ScrambledGamer** [AllTheMods/ATM-4#6]
I dont know whether its something to do with the modpack or minecraft itself but basically i went through the same portal a few times and i ended up appearing in a completely different location in the overworld. (it happened once I'm unable to recreate it)

**Comment by Yamza** [comment]
This can happen if it can't spawn the portal in the proper location when you go through. Portal moves too far to reconnect to the one you entered, thus sends you elsewhere.

**Comment by ScrambledGamer** [comment]
ah right so its a bug within the game itself
