### ISSUE TITLE
cant install 4-0.2.5

### ISSUE THREAD

**Issue by wiziekid** [AllTheMods/ATM-4#60]
if i try to install the 4-0.2.5 release on twitch i get an error on the "valadating manifest step" : system cant find the file. and it just stops the instal 
![Knipsel2](https://user-images.githubusercontent.com/58776741/70623707-fb5d1700-1c1e-11ea-8e76-59cac66abba7.PNG)

**Comment by TigerWalts** [comment]
Twitch is failing to install the version of Forge. The workaround is to install it manually.

You'll need to install the `forge-28-1-104` client manually into the Minecraft launcher installed by Twitch. The default location is:

- `C:\Users\<username>\Documents\Minecraft\Install`

A more in-depth guide is here:

- https://stickypiston.co/account/knowledgebase/142/Minecraft-114-Modpack-Fails-to-Install-on-Twitch---The-system-cannot-find-the-file-specified.html

**Comment by SylannaMaxwell** [comment]
Using ATLauncher is also an option, seems to work fine with installing on there.

**Comment by whatthedrunk** [comment]
Yeah this is a twitch issue the correct thing to do is what they said. The easiest being use one of these.
AtLauncher
https://atlauncher.com/downloads

GDLauncher
https://gdevs.io/
