### ISSUE TITLE
4-0.25 launch error | MultiMc Launcher

### ISSUE THREAD

**Issue by Bedonderd** [AllTheMods/ATM-4#61]
Hi i installed succesfully on MultiMC launcher, 
then added optifine version 1.14.4_HD_U_F5 and recieved error on launch attempt.

also installed fresh new instance of it and left the default optifine included and same error.

here is pastebin :
[Link](https://paste.ee/p/8zvwv#s=0)

pc specs:
Operating System
   Windows 10 Pro 64-bit
CPU
   Intel Core i7 @ 2.20GHz: Coffee Lake 14nm Technology
RAM
   16,0GB
Motherboard
   Wootware Computers P95xER (U3E1)
Graphics
   Generic PnP Monitor (1920x1080@144Hz)
   Intel UHD Graphics 630 (CLEVO/KAPOK Computer)
   4095MB NVIDIA GeForce GTX 1070 with Max-Q Design (CLEVO/KAPOK Computer): SLI Disabled

**Comment by whatthedrunk** [comment]
Multi MC does not support 1.14.4 try using these.

AtLauncher
https://atlauncher.com/downloads

GDLauncher
https://gdevs.io/
