### ISSUE TITLE
RFToolsStorage

### ISSUE THREAD

**Issue by ghost** [AllTheMods/ATM-4#62]
I was going in to try and make the Tier 1 Storage Module and it says "accept any forge:chest" but does not accept the oak chest from Quark.

**Comment by whatthedrunk** [comment]
It will be fixed when Quark pushes out an update. For now make your chests with different types of wood.

**Comment by whatthedrunk** [comment]
I see the update is actually out now if you manually update quark. I will have a new update out soon.
