### ISSUE TITLE
[Crafting] Any recipe that includes chests not accepting Quark Chests

### ISSUE THREAD

**Issue by alimoncul** [AllTheMods/ATM-4#71]
I can't use Quark Chests in recipes that needs chest.

**Comment by Uginsecond** [comment]
For crafting simple chest - use different sorts of wood...

**Comment by alimoncul** [comment]
I know that but they need to change crafting recipes for this.

**Comment by whatthedrunk** [comment]
Update to the newest version and that should fix this. There was an issue with Quark that was fixed. If you are still having issues let me know.
