### ISSUE TITLE
0.2.6 Crash on startup

### ISSUE THREAD

**Issue by Peca21** [AllTheMods/ATM-4#73]
I just downloaded ATM 4 for the first time and the game crashed during "constructing mods".

[Pastebin crash](https://pastebin.com/YA2CzWYQ)

**Comment by K-9Nina** [comment]
I am also getting a crash on startup. I just downloaded this using the Twitch launcher. As soon as I click, play the games crashes.

**Comment by whatthedrunk** [comment]
A lot of users are having issues with twitch and 1.14.4. Try one of these until they fix there stuff.

Alternatives that support Twitch imports.
AtLauncher
https://atlauncher.com/downloads

GDLauncher
https://gdevs.io/
