### ISSUE TITLE
Mystical Agriculture config

### ISSUE THREAD

**Issue by HamzaYazaw** [AllTheMods/ATM-4#81]
Hello everyone, I noticed that when wearing Superimun armor, it's suppose to give me "flight" 
Which they say in the modpack "Wearing a full set of Supremium Armor enables you to fly. (Configurable)" 
How can I configure that, and does it work in ATM-4?

**Comment by LezChap** [comment]
In the 1.14 version of Mystical Agriculture, there are no set bonuses for Armor like there were in 1.12.  You can still get flight (supposedly) by installing the Flight Augment.  I haven't tested this yet, still working on getting to it.

**Comment by HamzaYazaw** [comment]
> In the 1.14 version of Mystical Agriculture, there are no set bonuses for Armor like there were in 1.12. You can still get flight (supposedly) by installing the Flight Augment. I haven't tested this yet, still working on getting to it.

Ohh I see! Thank you, you have been great help
