### ISSUE TITLE
Crash when opening the Request Table from Simple Storage Network [version 0.1.0]

### ISSUE THREAD

**Issue by ScrambledGamer** [AllTheMods/ATM-4#9]
It's an issue with the mod, it needs to be downgraded down from 0.0.12 to 0.0.11 in order to make it functional again.

**Comment by Stray216** [comment]
does crash for me too (crash report https://pastebin.com/nHgd4g3M)

**Comment by whatthedrunk** [comment]
Should be fixed in the new version please let me know if you have any other issues.
