### ISSUE TITLE
Solar Flux Reborn causing crash on loading world

### ISSUE THREAD

**Issue by Asshall** [AllTheMods/ATM-4#97]
Here's the very explicit crash log : https://pastebin.com/NTuY332K

I can't see any issue related to the "Dispersive Upgrade" on the Solar Flux Reborn github.

**Comment by Uzkul** [comment]
I might have a similar problem.
My world with ATM4 is always stuck on 100% loading. If I remove the Solar FLux mod, the world loads in again.
So there is no actual crash, just a indefinate loading screen.

I passed this along to Zeiththewolf on his discord, but he can't see a problem in the logs.

If I save my world without Solar Flux, then add solar flux to the mods list again and try to load the world. it once again keep getting stuck at 100% loading.
So I can now only load the modpack withjout Solar Flux Reborn in it.

**Comment by Uzkul** [comment]
Solar FLux Reborn just had an update to 14.1.4 and that fixed my issue. Might want to give that a try in your modpack

**Comment by Asshall** [comment]
Indeed it seems to be working just fine ;)
Thank you good sir :1st_place_medal:
